Feature/upload apropiaciones
udistrital/carga-rubros-mongo pull request #2
Opened 2022-04-14 02:25 UTC by brayanpasa99

Resuelve: udistrital/financiera_documentacion#411

2022-04-14 21:59 UTC, AlexFBP requested changes
En general, bien
- Dado que este repo no está pensado para ser una API sino para cargar datos al sistema, el swagger/OpenAPI es innecesario: Eliminar los archivos swagger/*, y colocar en el .gitignore una nueva línea con: `swagger/**`
- Se agregaron algunos _suggested changes_ menores, se pueden aplicar via web
- (Recomendado) Respecto al uso de Logger, se pueden dejar descomentados todos los `Logger.algo()` y en el main.ts definir el nivel de logging - [Referencia](https://docs.nestjs.com/techniques/logger#basic-customization) - Donde dice _"To enable specific logging levels, set ..."_
- (Recomendado) Donde se puedan evitar los tipos `any[]`, mejor

2022-04-14 21:59 UTC, AlexFBP commented on src/modules/plan-adquisiciones/entities/registroPlanAdquisiciones.entity.ts
>    }
```suggestion
  }

```

2022-04-14 21:59 UTC, AlexFBP commented on src/modules/plan-adquisiciones/helpers/info-plan-adquisiciones-helper/info-plan-adquisiciones-helper.service.ts
> +    dataSheetCalc[0]['FUENTE DE LOS RECURSOS'];
Tomar este valor de una constante, puede ser declarada inmediatamente antes de la L59, y consumida no solo en ella sino en la L65

2022-04-14 22:00 UTC, AlexFBP commented on .develop.env
> +export TIPOMOVIMIENTOID=33
```suggestion
export TIPOMOVIMIENTOID=33

```

2022-04-15 01:14 UTC, brayanpasa99 commented on src/modules/plan-adquisiciones/helpers/info-plan-adquisiciones-helper/info-plan-adquisiciones-helper.service.ts
> +    dataSheetCalc[0]['FUENTE DE LOS RECURSOS'];
Se elimina la línea 59 y la línea 65 permanece igual debido a que no tienen ninguna relación y los valores utilizados son declarados en constantes.

2022-04-15 01:29 UTC, brayanpasa99 commented
Tuve algunos problemas con el merge, pero ya subí la rama actualizada

2022-04-17 21:10 UTC, AlexFBP approved these changes

2022-04-17 21:10 UTC, merged